apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: payments-platform
  namespace: payments
spec:
  interval: 30m
  chart:
    spec:
      chart: ./payments-platform
      sourceRef:
        kind: GitRepository
        name: payment-processor
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 2

    image:
      repository: ghcr.io/grendel71/payment-processor
      pullPolicy: IfNotPresent
      tag: "sha-8d0e80e"

    database:
      existingSecret:
        name: paymentprocessor-db
        key: DATABASE_URL

    migrations:
      enabled: true

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    autoscaling:
      enabled: false

    networkPolicy:
      enabled: true
      ingress:
        namespaceSelector:
          kubernetes.io/metadata.name: envoy-gateway-system
        podSelector:
          app.kubernetes.io/name: envoy-gateway
      egress:
        dnsNamespaceSelector:
          kubernetes.io/metadata.name: kube-system
        dnsPodSelector:
          k8s-app: kube-dns
        database:
          podSelector:
            cnpg.io/cluster: payments-db
          namespaceSelector:
            kubernetes.io/metadata.name: payments
          port: 5432