apiVersion: ENC[AES256_GCM,data:ynk=,iv:4Tjg+1BSYVIEseAqdo5LdjyOKcu73G6r+0DD0p6X3fQ=,tag:mBaoPsX0zvVK4f6t7T5pEg==,type:str]
kind: ENC[AES256_GCM,data:KzeNB0ef,iv:+EFze9gWRmOjp7O+swsG/QK7SxQEbI+5sS7aRD7/mks=,tag:WIXLsmVFAMO/DWhYnzfDEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0fwZoxGkDDYLFirunBHIsBYpqZ9tEEE=,iv:A3wVzJQlEqec2WX6JxQzohOmnWdN6/1MEJ3NhOLyONw=,tag:MtbKUwD+LWZM68Hz4c3pxg==,type:str]
    namespace: ENC[AES256_GCM,data:IjE5NvF4hqI=,iv:8C07B5OoJyRfDnRQWXkGG5hBwQYpSM7li4QbWGfSAzY=,tag:stPNhMNTz1Sggj9f078d/w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:9jFoL3jRsvtI6INQ0l1Raw==,iv:ZOM81M2tTlnoxkLy2eXH+AzXG+mKrNmLAkmExPA6cv4=,tag:Oec92lWNiDm3tgdmBrXc8w==,type:str]
    password: ENC[AES256_GCM,data:eO6/29fTmAVSSuOKImE1xA5vQcfya9tV7lthpGNljn4=,iv:UyqqrGzTmD8UxSpsc7h/UY3Vr+4hjOVmPa1X2YzYqnk=,tag:MAPWh4G2SBc6Dg2ZUxR6Wg==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bEY5dStNSHZzS25GYVZu
            R2dCdTNtay83TWlnTVFOVi9UaURaZG0rSjJnCkZRcm5HeFA5MCtjYStHTWNvUSt2
            Z29nR3RVd3NTVkVLTUlzUFIxZ3IvUDgKLS0tIC9zUk9BVmJObHhCMitaNUhCQko2
            aGRmYzR1WFRzTmhzMTRIbTlCek1pcjQKWQous22vrdrrzLkwkvGw5CcakmZ1iv1w
            P9f0TRfhQcYXIzZ3947KeBgaGjGYcq5G1Bda+esAuCrC4x212UU23w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T02:35:03Z"
    mac: ENC[AES256_GCM,data:oYXLHrGfFBQIyZMdBUdtuhBPmO2pDywH2U+tPPnboGNOcrpEv/1n7S9So/oMkzrPji8NjNPchuKF1lUBf3vxdkXjp/qYsXdePHK/9YxPywE+sZylgSML8QKOTxpcdahh4kJWBqTYZ93chpbEfYFtffgr23Y5cC4n5h0Yba48Ox8=,iv:zAxFBaDkPq1PKKzQGvdNQESifWAEd1md77WXGAeUpfo=,tag:dwuqMTIUM2zXoIX0Cdf8fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:Jko=,iv:Lf3cimMvUV0f+vCy5gCJ6fkmwiy+IepKBxFmP4MOVXI=,tag:vrAnZNFXVDRK3gADkMcVdg==,type:str]
kind: ENC[AES256_GCM,data:au5hqb/A,iv:7ivnaR8sjhSczHz2LrA5lYzOOlRgLPQsTwUApDPrjG4=,tag:S1gySC87mjq0rOWyWzylLQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lAGbgoIgOFQGM/rXYhJxFlFJ4A==,iv:W4Xj+ivrkDWNJdB0eAFYpghYd/W0G/sH5zW8q1ai1DM=,tag:VSyb8gQP8UPdwwzp0MzOBA==,type:str]
    namespace: ENC[AES256_GCM,data:hQXiaaNy5d4=,iv:sLXoHvWltVqq5MAI0u/RmnxqZh8BoyEGtvRr2yAiKSE=,tag:cIH4f00LjSm7tyi5nGpzHQ==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Ean3nCI1P30DaHSlPfpwDr1m+24FkGWTigqoCjF/VIOPZS7B37HQKP/Zj/jElQqV/ELxWDWnQQ2THcrM8LxT3cRWv84gaAZPGwIkGzhqbtBcqXOMhQgiayVogu4kZkP1qLYsF7Gm1PuVS0Ppl/Ppe9Z/WBBJW5wYLtuErD1mX0AiUmN5Vyqu,iv:kkKzhqbBlsWZtVHNDX9SV3G9Buc+PsduhuCRI4vkloE=,tag:feSZcmjPCbyatw7PURkVTg==,type:str]
sops:
    age:
        - recipient: age1jc2yh5yr5xdmgfu46q42z3pxy0aztn94x5hsarzmjwxzt9f4tq3qtsmrup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bEY5dStNSHZzS25GYVZu
            R2dCdTNtay83TWlnTVFOVi9UaURaZG0rSjJnCkZRcm5HeFA5MCtjYStHTWNvUSt2
            Z29nR3RVd3NTVkVLTUlzUFIxZ3IvUDgKLS0tIC9zUk9BVmJObHhCMitaNUhCQko2
            aGRmYzR1WFRzTmhzMTRIbTlCek1pcjQKWQous22vrdrrzLkwkvGw5CcakmZ1iv1w
            P9f0TRfhQcYXIzZ3947KeBgaGjGYcq5G1Bda+esAuCrC4x212UU23w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T02:35:03Z"
    mac: ENC[AES256_GCM,data:oYXLHrGfFBQIyZMdBUdtuhBPmO2pDywH2U+tPPnboGNOcrpEv/1n7S9So/oMkzrPji8NjNPchuKF1lUBf3vxdkXjp/qYsXdePHK/9YxPywE+sZylgSML8QKOTxpcdahh4kJWBqTYZ93chpbEfYFtffgr23Y5cC4n5h0Yba48Ox8=,iv:zAxFBaDkPq1PKKzQGvdNQESifWAEd1md77WXGAeUpfo=,tag:dwuqMTIUM2zXoIX0Cdf8fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
