"""initial schema

Revision ID: 6ed9acea6544
Revises: 
Create Date: 2026-06-19 04:37:48.689560

"""
# NOTE: post-autogenerate edits:
# - Changed audit_events.payload column from sa.JSON() to postgresql.JSONB().
#   Autogenerated sa.JSON() materializes as plain `json` on Postgres, but the
#   design spec (§4.4) requires JSONB for binary storage, GIN-indexability, and
#   efficient `->>` access. The model still uses generic `JSON` in code, which
#   SQLAlchemy reads/writes transparently against a JSONB column.
# - Added explicit DROP TYPE statements for the 3 native PG enum types
#   (payment_status, ledger_entry_type, audit_event_type) in downgrade().
#   Autogenerate only dropped the tables, leaving the enum types as orphans
#   after a downgrade — breaking idempotent re-upgrade and violating the
#   "downgrade must fully reverse upgrade" contract.
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6ed9acea6544'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'settled', 'failed', name='payment_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'idempotency_key', name='uq_merchant_idempotency')
    )
    op.create_index(op.f('ix_payments_merchant_id'), 'payments', ['merchant_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('payment_created', 'settlement_initiated', 'settlement_succeeded', 'settlement_failed', name='audit_event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_payment_id'), 'audit_events', ['payment_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.Enum('debit', name='ledger_entry_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_payment_id'), 'ledger_entries', ['payment_id'], unique=False)
    op.create_table('settlement_payments',
    sa.Column('settlement_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('settlement_id'),
    sa.UniqueConstraint('payment_id', name='uq_settlement_payment_payment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_payments')
    op.drop_index(op.f('ix_ledger_entries_payment_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_audit_events_payment_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_payments_merchant_id'), table_name='payments')
    op.drop_table('payments')
    # Drop native PG enum types after all tables that reference them are gone.
    # Order: payment_status (payments), ledger_entry_type (ledger_entries),
    # audit_event_type (audit_events). All three must be dropped explicitly —
    # PG does not cascade-drop enum types when their table is dropped.
    op.execute("DROP TYPE IF EXISTS payment_status CASCADE")
    op.execute("DROP TYPE IF EXISTS ledger_entry_type CASCADE")
    op.execute("DROP TYPE IF EXISTS audit_event_type CASCADE")
    # ### end Alembic commands ###
